import type { Metadata } from 'next';
import React from 'react';

import ReduxProvider from '@/ducks/provider';
import { WalletConnectProvider } from '@/lib/walletConnectProvider';

import './globals.css';
import { TamaguiProvider } from '@/lib/tamaguiProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <WalletConnectProvider>
            <TamaguiProvider>{children}</TamaguiProvider>
          </WalletConnectProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
