import type { Metadata } from 'next';

import ReduxProvider from '@/ducks/provider';
import { Web3Modal } from '@/lib/Web3Modal';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <Web3Modal>{children}</Web3Modal>
        </ReduxProvider>
      </body>
    </html>
  );
}
